version: "3.8"
services:
    db_postgres:
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: localhost
            POSTGRES_DB: produccion
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db_postgres-data:/var/lib/postgresql/data
        ports:
        - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: domi@domi.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8090:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db_postgres:pgsql-server"
        depends_on:
            - db_postgres
volumes:
    db_postgres-data:
    pgadmin-data: