spring.profiles.active=prod
server.servlet.context-path=/ezyshop/api
logging.level.org.springframework.security.web.*=debug

server.port=8081
spring.datasource.driverClassName=org.postgresql.Driver

 #KEY JWT
key.jwt=Ezyshop
 #Depurar
spring.boot.devtools.remote.debug=true

 #Paypal
paypal.mode=sandbox
paypal.client.id=
paypal.client.secret=

 #Cloudinary
cloud.name=
api.key=
api.secret=
api.env.variable=

 #Consultas
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
